export const ADD_CAMPAIGN = 'ADD_CAMPAIGN';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const EDIT_CAMPAIGN = 'EDIT_CAMPAIGN';
export const LOGIN = 'LOGIN';
const configKeys = require('../config/keys');
export const CALLBACK_URL = configKeys.callbackUrl;

const data = {
  en: {
    brand: "FPT Corporation",
    inform_1: "FPT 2020 ANNUAL",
    inform_2: "GENERAL MEETING",
    inform_3: "OF SHAREHOLDERS",
    date_time: "1:00 pm, 08/04/2020 at F-Ville 2, Hoa Lac Hi-Tech Park, Hanoi ",
    program_button: "Agenda",
    doc_button: "Document",
    reg: "Sign up",
    live_button: "Offline",
    note_live: "* At F-Ville 2, Hoa Lac Hi-Tech Park, Ha Noi",
    online_button: "Online",
    note_online: "* Follow remotely via live webinar and/or remote voting",
    id_command: "Take/ Upload a photo of the front of your ID card",
    id_command2: "Take/ Upload a photo of the front of your passport",
    next_button: "Next",
    recap_button: "ReCapture",
    id_take_button: "Camera/Upload",
    id_take_button_2: "Camera/Upload",
    face_take_button: "Camera/Upload",
    face_take_button_pc: "Camera",
    confirm_command: "Please re-verify your information",
    prev_button: "Back",
    prev_button_break: "< Back",
    plc_id: "ID number",
    plc_name: "Full name",
    plc_dob: "Date of Birth",
    plc_town: "Domicile",
    plc_addr: "Permanent address",
    face_command: "Take/ Upload a photo of the front of your ID card",
    email_command: "Please enter your email address",
    success_command: "Succeeded",
    msg_command1: "Thank you, Please check your email and follow the instructions to verify your address ",
    msg_command2: "We will send instructions for remote voting / live webinar to the email address provided as soon as possible.",
    type_sh_command: "Please select one of the following options",
    type_sh_1: "Domestic Individual shareholders",
    type_sh_2: "Foreign individual shareholders",
    type_sh_3: "Organization shareholder",
    type_select_command: "Dear shareholder ",
    type_select_command2: " (",
    type_select_command3: "), please select the method of participation ",
    type_select_note: "(choose one or both)",
    type_select_checkbox1: "Remote voting",
    type_select_checkbox2: "Via live webinar",
    confirm_live_command: "Please verify your information",
    plc_name_l: "Full name/Organization name",
    plc_name_o: "Organization name",
    plc_type_l: "ID number/registration number",
    plc_type_o: "Registration number",
    plc_phone: "Phone number",
    success_live_command: "Thank you and see you at 1:00 pm at F-Ville 2, Hoa Lac Hi-Tech Park, km 29 Thang Long Boulevard, Thach That, Hanoi",
    success_live_title: "You have signed up successfully",
    note_lp_1: "Hotline: ",
    note_lp_2: "+84 24 7300 7300/ ext  46496",
    note_lp_3: "(For more convenience, please sign up using mobile devices)",
    alert_1: "ReTake/ ReUpload a photo of the front of your ID card!",
    alert_2: "Your information is not available in the data. Please try again by following the instructions or call for suppor: +84 24 7300 7300/số máy lẻ 46496",
    alert_7: "Please fulfill your details",
    alert_3: "Incorrect face detection!",
    alert_4: "Please select at least one of methods of participation!",
    alert_5: "Invalid email or phone number!",
    alert_6: "Camera not detected!",
    notify: "Notification",
    confirm: "Confirm",
    button_finish: "Finish",
    note_id_command: "* Please use your ID card in the registration form of Shareholders",
    note_confirm_command: "* Please use your ID number/registration number in the registration form of Shareholders",
    note_confirm_command_o: "* Please use your registration number in the registration form of Shareholders",
    note_email_command: "* This email is used for communication with shareholders ",
    home_button: "Home Page",
    doc_1: "Invitation letter to FPT's 2020 AGM",
    doc_2: "Letter of Authorization attend at FPT’s AGM of Shareholders 2020",
    doc_3: "Regulation on convening and voting at FPT's 2020 AGM",
    doc_4: "2019 Annual Report",
    doc_5: "FPT's 2020 AGM documentary",
    link_1: "https://fpt.com.vn//Images/files/cong-bo/2020/%C4%90H%C4%90C%C4%90-2020/1_-Invitation-Letter-2020_1732020.pdf",
    link_2: "https://fpt.com.vn//Images/files/cong-bo/2020/%C4%90H%C4%90C%C4%90-2020/3_-Power-of-Attorney-2020_final-1732020.doc",
    link_3: "https://fpt.com.vn//Images/files/cong-bo/2020/%C4%90H%C4%90C%C4%90-2020/3_-Quy-trinh_TA.pdf",
    link_4: "https://fpt.com.vn//Images/files/cong-bo/2020/Thang-3/AR-2019_web.pdf",
    link_5: "https://fpt.com.vn//Images/files/cong-bo/2020/Thang-3/Tai-lieu_web_TA.pdf",
    button_live_alert_1: "To:   Shareholders",
    button_live_alert_2: "Due to the COVID-19 outbreak, the Chairman of Hanoi City People's Committee demands restriction on people gathering. Hence, the Company encourages Shareholders to register for remote voting and join the live webinar. ",
    button_live_alert_3: "Yours respectfully,",
    button_live_alert_4: "FPT Corporation",
    button_live_alert: "Continue offline registration"

  },
  vi: {
    brand: "Công Ty Cổ Phần FPT",
    inform_1: "Đại hội đồng cổ đông",
    inform_2: "Thường niên FPT 2020",
    inform_3: "",
    date_time: "13h00, ngày 08/04/2020 tại F-Ville 2, Khu Công nghệ cao Hòa Lạc, Hà Nội",
    program_button: "Chương trình",
    doc_button: "Tài liệu",
    reg: "Đăng ký",
    live_button: "Trực tiếp",
    note_live: "* Tại F-Ville 2, Khu Công nghệ cao Hòa Lạc, Hà Nội",
    online_button: "Trực tuyến",
    note_online: "* Theo dõi trực tuyến hoặc bỏ phiếu từ xa",
    id_command: "Chụp lại ảnh CMND/Thẻ căn cước mặt trước của bạn",
    id_command2: "Chụp lại ảnh Hộ chiếu mặt trước của bạn",
    next_button: "Tiếp theo",
    recap_button: "Chụp lại",
    face_take_button: "Tải/chụp ảnh khuôn mặt",
    face_take_button_pc: "Chụp ảnh khuôn mặt",
    id_take_button: "Tải ảnh/chụp ảnh CMND",
    id_take_button_2: "Tải ảnh/chụp ảnh hộ chiếu",
    confirm_command: "Xác minh lại thông tin của bạn",
    prev_button: "Quay Lại",
    prev_button_break: "< Quay Lại",
    plc_id: "Số CMND/CCCD",
    plc_name: "Họ và Tên",
    plc_dob: "Ngày sinh",
    plc_town: "Nguyên quán",
    plc_addr: "Hộ khẩu",
    face_command: "Chụp lại ảnh khuôn mặt của bạn",
    email_command: "Nhập email của Quý Cổ đông",
    success_command: "Gửi thông tin thành công",
    msg_command1: "Cảm ơn Quý Cổ đông! Vui lòng kiểm tra email và làm theo hướng dẫn để xác thực địa chỉ",
    msg_command2: "Công ty sẽ gửi hướng dẫn việc bỏ phiếu từ xa/ theo dõi trực tuyến đến địa chỉ email của Quý Cổ đông trong thời gian sớm nhất",
    type_sh_command: "Vui lòng lựa chọn một trong các thông tin dưới đây",
    type_sh_1: "Cổ đông cá nhân trong nước",
    type_sh_2: "Cổ đông cá nhân nước ngoài",
    type_sh_3: "Cổ đông là tổ chức",
    type_select_command: "Xin chào Quý Cổ đông ",
    type_select_command2: " (",
    type_select_command3: "). Xin vui lòng lựa chọn hình thức tham dự",
    type_select_note: "(chọn một trong hai hoặc cả hai)",
    type_select_checkbox1: "Bỏ phiếu từ xa",
    type_select_checkbox2: "Xem trực tuyến",
    confirm_live_command: "Vui lòng xác minh thông tin",
    plc_name_l: "Họ và tên/ Tên tổ chức",
    plc_name_o: "Tên tổ chức",
    plc_type_l: "CMND/CCCD/GPĐKKD",
    plc_type_o: "GPĐKKD",
    plc_phone: "Điện thoại",
    success_live_command: "Xin cảm ơn và hẹn gặp Quý Cổ đông vào 13h00 tại F-Ville 2, Khu Công nghệ cao Hòa Lạc, km 29 Đại lộ Thăng Long, Thạch Thất, Hà Nội",
    success_live_title: "Đăng ký thành công",
    note_lp_1: "Hỗ trợ: ",
    note_lp_2: "+84 24 7300 7300/số máy lẻ 46496",
    note_lp_3: "(Để thuận tiện, Cổ đông nên sử dụng mobile để đăng ký)",
    alert_1: "Xin hãy chụp/tải lại ảnh CMT của bạn!",
    alert_2: "Thông tin của bạn không có trong dữ liệu, Vui lòng làm lại theo hướng dẫn hoặc gọi hỗ trợ: +84 24 7300 7300/số máy lẻ 46496",
    alert_7: "Hãy điền đầy đủ thông tin của bạn",
    alert_3: "Nhận diện khuôn mặt không đúng!",
    alert_4: "Xin hãy chọn ít nhất một lựa chọn!",
    alert_5: "Email hoặc số điện thoại không hợp lệ!",
    alert_6: "Không tìm thấy camera!",
    notify: "Thông báo",
    confirm: "Xác nhận",
    button_finish: "Hoàn tất",
    note_id_command: "* Vui lòng sử dụng CMND trong bản Đăng ký cổ đông ",
    note_confirm_command: "* Vui lòng sử dụng số CMND/CCCD/GPĐKKD trong bản Đăng ký cổ đông ",
    note_confirm_command_o: "* Vui lòng sử dụng số GPĐKKD trong bản Đăng ký cổ đông ",
    note_email_command: "* Email này sẽ dùng cho BTC liên lạc với Cổ Đông ",
    home_button: "Trở về trang chủ",
    doc_1: "Thông báo mời họp Đại hội đồng cổ đông thường niên 2020",
    doc_2: "Giấy ủy quyền tham dự ĐHĐCĐ thường niên năm 2020",
    doc_3: "Quy trình về trình tự, thủ tục triệu tập, biểu quyết tại ĐHĐCĐ thường niên 2020",
    doc_4: "Báo cáo thường niên năm 2019",
    doc_5: "Tài liệu Đại hội đồng cổ đông thường niên 2020",
    link_1: "https://fpt.com.vn//Images/files/cong-bo/2020/%C4%90H%C4%90C%C4%90-2020/1_-Thong-bao-moi-hop-2020_final-1732020.pdf",
    link_2: "https://fpt.com.vn//Images/files/cong-bo/2020/%C4%90H%C4%90C%C4%90-2020/3_-Giay-uy-quyen-hop-DHCD-2020_final-1732020.doc",
    link_3: "https://fpt.com.vn//Images/files/cong-bo/2020/%C4%90H%C4%90C%C4%90-2020/3_-Quy-trinh_TV.pdf",
    link_4: "https://fpt.com.vn//Images/files/cong-bo/2020/Thang-3/Bao-cao-thuong-nien-2019_TV.pdf",
    link_5: "https://fpt.com.vn//Images/files/cong-bo/2020/Thang-3/Tai-lieu_web_TV.pdf",
    button_live_alert_1: "Kính gửi Quý Cổ đông:",
    button_live_alert_2: "Do tình hình diễn biến phức tạp của dịch COVID-19, Chủ tịch UBND thành phố Hà Nội yêu cầu hạn chế tập trung đông người, Công ty khuyến nghị Quý Cổ đông chuyển sang hình thức bỏ phiếu từ xa và theo dõi trực tuyến Đại hội. ",
    button_live_alert_3: "Trân trọng, ",
    button_live_alert_4: "Công ty Cổ phần FPT",
    button_live_alert: "Tiếp tục đăng ký trực tiếp"

  }
};
export {data};
